---
name: Publish RPMs
on:
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      ref:
        description: 'branch ref'
        required: true
        default: 'master'
      branch:
        description: 'branch name'
        default: 'master'
        required: false

jobs:
  rpmbuild_el7:
    name: Build an EL7 rpm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code tree
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{github.event.inputs.branch}}

      - name: Run the build in a container (SL7/HEPCloud-CI)
        uses: ./.github/actions/python-command-in-sl7-container
        with:
          python-command: 'setup.py bdist_rpm'
          logfile: 'rpmbuild.log'

      - name: Archive rpm
        uses: actions/upload-artifact@v2
        with:
          name: rpms
          path: dist/*.rpm
          if-no-files-found: error
          
      - name: Check variables
        run: |
          echo "ref: ${GITHUB_REF}"
          echo "branch: ${{github.event.inputs.branch}}"
          echo "ref: draft-${GITHUB_REF##*/}${{github.event.inputs.branch}}"
          myREF_tmp="${{github.event.inputs.branch}}"
          echo "ref: draft-${myREF_tmp:-${GITHUB_REF##*/}}"
          pwd
          ls dist
          
      - name: Upload RPMs
        run: |
          set -x
          myREF_tmp="${{github.event.inputs.branch}}"
          echo "ref: draft-${myREF_tmp:-${GITHUB_REF##*/}}"
          hub release delete "draft-${myREF_tmp:-${GITHUB_REF##*/}}" || :
          assets=()
          for asset in ./dist/*.rpm; do
            assets+=("-a" "${asset}")
          done
          hub release create -p "${assets[@]}" \
              -m "RPMs for ${myREF_tmp:-${GITHUB_REF##*/}} branch" \
              "draft-${myREF_tmp:-${GITHUB_REF##*/}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
